namespace SpriteKind {
    export const UI = SpriteKind.create()
}
color.FadeToWhite.startScreenEffect(500)
timer.after(3000, function () {
    color.startFadeFromCurrent(color.originalPalette, 500)
})
pause(2500)
music.setVolume(160)
music.play(music.createSong(hex`0078000408020100001c00010a006400f4016400000400000000000000000000000000050000040600000004000106`), music.PlaybackMode.LoopingInBackground)
let title = sprites.create(img`
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffddddddddddddddddddddddddddddddddddddddddddffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffddddddddddddddddddddddddddddddddddddddddddffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffddddddddddddddddddddddddddddddddddddddddddffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffddddddddddddddddddddddddddddddddddddddddddffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffddddddddddddddddddddddddddddddddddddddddddfffffffffffffffffffffffffffddfffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffdddddddddddddddddddddddddddddddddddddddddddddddddfffffffffffffffffffffddffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffdddddddddddddddddddddddddddddddddddddddddddddddddfffffffffffffffffffffddffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffdddddddddddddddddddddddddddddddddddddddddddddddddfffffffffffffffffffffddffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffdddddddddddddddddddddddddddddddddddddddddddddddddfffffffffffffffffffffddffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffdddddddddddddddddddddddddddddddddddddddddddddddddffffffffffffffffdfdffddffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffdddddddddddddddddddddddddddddddddddddddddddddddffffffffffffffffffffffdddffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffddddddddddddddddddddddddddddddddddddddddddddddddddddfffffffffffffffdddddffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffddddddddddddddddddddddddddddddddddddddddddddddddddddffffffffdfffffddddddffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffdddddddddddddddddddddddddddddddddddddddddddddddffffffffffffddfffffdfddddffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffdddddddddddddddddddddddddddddddddddddddddddddddfffffffffddffdddddfffdfddffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffdddddddddddddddddddddddddddddddddddddddddddddddddddddfffddddddddfffddfddffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffdddddddddddddddddddddddddddddddddddddddddddddddddddddffddddddddffddddfddffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffdddddddddddddddddddddddddddddddddddddddddddddddddddddffddddddfdddddddfddffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffdddddddddddddddddddddddddddddddddddddddddddddddddddddffdddddddddddddddddffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffdddddddddddddddddddddddddddddddddddddddddddddddddddddffdddddddddddddddddffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffddddddddddddfffffddddddddddddddddddddddddddddddddddddfffdddddddddddfddddffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffdddddddddddfffffffffffffffffffffffffffffffffdfdddddddffddddddddddddfddddffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffddddddddddffffffffffffffffffffffffffffffffffffddddddffddddddddddddfddddffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffddddddddddffffffffffffffffffffffffffffffffffffddddddffddddddddddddfddddffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffddddddddddffffffffffffffffffffffffffffffffffffddddddffddddddddddfdfdddddfffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffdddddddddddffffffffffffffffffffffffffffffffffffddddddffdddddddddffffdddddfffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffdddddddddddffffffffffffffffffffffffffffffffffffddddddfddddddddddfffddddddfffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffddddddddddddfffffffffffffffffffffffffffffffffffddddddfddddddddddffdddddddfffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffddddddddddddfffffffffffffffffffffffffffffffffffddddddfddddddddddffdddddddfffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffddddddddddddfffffffffffffffffffffffffffffffffffddddddfddddddddddddddddddddffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffddddddddddddfffffffffffffffffffffffffffffffffffddddddfddddddddddddddddddddffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffddddddddddddfffffffffffffffffffffffffffffffffffddddddfddddddddddddddddddddffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffddddddddddddfffffffffffffffffffffffffffffffffffddddddfddddddddddddddddddddffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffddddddddddddfffffffffffffffffffffffffffffffffffddddddfddddddddddddddddddddffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffddddddddddddfffffffffffffffffffffffffffffffffffddddddfddddddddddddddddddddddffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffddddddddddddfffffffffffffffffffffffffffffffffffddddddfddddddddddddddddddddddffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffddddddddddddfffffffffffffffffffffffffffffffffffddddddfddddddddddddddddddddddffffffffffffffffffffffffffffffffffffffffff
    fffffffffffdffffffffffffffffffffffffffffffddddddddddddfffffffffffffffffffffffffffffffffffddddddfddddddddddddddddddddddddddddddddffffffffffffffffffffffffffffffff
    ffffffffffddffffffffffffffffffffffffffffffddddddddddddfffffffffffffffffffffffffffffffffffddddddfddddddddddddddddddddddddddddddddffffffffffffffffffffffffffffffff
    ffffffffffddfffffffffffffffffffffffffffffffdddddddddddfffffffffffffffffffffffffffffffffffddddddfdddddddddddddddddddddddddddddddddfffffffffffffffffffffffffffffff
    fffffffffdddfffffffffffffffffffffffffffffffdddddddddddfffffffffffffffffffffffffffffffffffddddddfdddddddddddddddddddddddddddddddddfffffffffffffffffffffffffffffff
    fffffffffbdcfcbbbbbcbbbbbfbbbfcbcffffffbbffdbdbddcbbdcbbfffffbbbfffcddcfffcddcfffffffffffddddddfdddddddddddddddddddddddddddddddddfffffffffffffffffffffffffffffff
    fffffffc1111dd11111d11111c111f11bfffffd11fc11111dd11d111ffffb111cfd1111bfd1111bffffffffffddddddfdddddddddddddddddddddddddddddddddfffffffffffffffffffffffffffffff
    fffffffd11111d11111d11111c111b11bfffb1111fb11111cd11d111ffffb111bf11111df111111ffffffffffddddddfdddddddddddddddddddddddddddddddddfffffffffffffffffffffffffffffff
    fffffff111c11d11fffd11fffc111d11bfffb1111f111d11dd11d111ffffd111bc11bd11c11bd11ffffffffffddddddddddddddddddddddddddddddddddddddddfffffffffffffffffffffffffffffff
    fffffff111cddd11fccd11fccc111111bfffffd11f111d11dd11d111ffff1111db11cb11b11cb11cfffffffffddddddddddddddddddddddddddddddddddddddddfffffffffffffffffffffffffffffff
    fffffdfb111ccd11ddbd11ddbc111111bccfffd11c111d11dd11d111ccff11111b11bbbbb11cb11ccffffffffddddddddddddddddddddddddddddddddddddddddfffffffffffffffffffffffffffffff
    fffffddf1111cd1111dd1111dc111111bccfffd11c111c11dd111111ccfc11d11b11d111b11bd11cccfffffffddddddddddddddddddddddddddddddddddddddddfffffffffffffffffffffffffffffff
    fffffdddd111dd11d1bd11d1bc111111bccfffd11c111c11dd11d111cccb11b11b11d111b11bd11cccfffffffddddddddddddddddddddddddddddddddddddddddfffffffffffffffffffffffffffffff
    ffdffddfdc111d11cccd11cccc11d111bccfffd11f111c11dd11c111cccb11d11d11bd11b11bd11cccfffffffdddb11dddddddddddddddddddddddddddddb1dddffffffffffb1ffffffffff1bfffffff
    fddfddd11bb11111cccd11cccc11c111bccfffd11f111c11dd11c111cccd11111d11bd11b11bd11cccfffffffdddb111bddcddcdddccdddcddddddcdddddb1ddccffffffcffd1fffcffffcf1dfffffff
    fddfddd111d11d11bbcd11bbcc11c111bccfffb11fd11b11dd11c111ccc111111d11d111c11d111cccfffffffdddb1d1dd11cd11cb11cd111ddddd11cddc111c11dffffd11c111c111fd11d11bffffff
    fddfdddd11111d11111d11111c11cd11bccfffb11fb11111cd11c111ccc11bf11111111dc11111dcccfffffffdddb1d1dd1bc1d1d111db1d1cddc1d1ddddd1cd1d1fffc1d1bd1cb1d1bd1bc1dcffffff
    fddddddcd111bd11111d11111c11cb11bccfffb11fcd111dcd11c111ccc11bfd11b1111ccb1111ccccfffffffdddb1d1dd1db1c1d11d1b1b1bddc1c1ddddd1d11b1cffc1d1dd1fb1c1bd1ff1dfffffff
    fddddddfddccccccccccffccccfffccccccfffffffccccccccccccccccfffffccccccccccccccccccffffffffdddb111bd1db111dd1dcc11cddddb11ddddd1d11b1cfffd1bfd1fcd11bd1ff1dfffffff
    fddddddddddccccccccccccccccffccccccffffffffdddcccccddcccccfffffcccccccccccfffccccffffffffdddb1dbcd1cb1bbbcd1dcc11ccdc1b1dcddd1d11b1ccfff11bd1fd1b1bd1ff1dfffffff
    fddddddfdddddcffffccfffcccffffffffffffffffffddddcddddddffffffffffffffffccfffffccfffffffffdddb1cdcd1cb1b1d1d11b1b1bcdb1c1dccdd1d11b1ccfc1b1dd1fd1c1bd1cf1dfffffff
    fdddddddddddddffffffffffffffffffffffffffffffdddddddddddfffffffffffffffffffffffffffffffffddddb1cdcd1dc1d1d1111b1d1bcdc1d1dccdd1cd1d1ccff1d1dd1cd1d1bd1cf1dcffffff
    fdddddddddddddfffffffffffffffffffffffffffffddddddddddddfffffffffffffffffffffffffffffffddddddb1dddd1dd111cb11bc111ccdd111dccdb11b11dccffd11bb11c111bd1cf11bffffff
    fdddddddddddddfffffffffffffffffffffffffffffddddddddddddffdddfffffffffffffffffffffffffffdddddddddddddddcdccccccccdccddddddccdddddcccccffffffcccffffccccffcfffffff
    fdddddddddddddfffffffffffffffffffffffffffffddddddddddddffcd1ffffffffffffffc1fffffffffffffddddddddddddddddccddccdddcddddddccddddddffccffffffccfffffcccfffffffffff
    fdddddddddddddffffffffffffcfffffcffffcffffcdddddcddddcdfffb1fffffcffffcfffb1fffffcfffffffddddddddddddddddddddddddddddddddfdddddddfffffffffffffffffffffffffffffff
    fdddddddddddddffffd111bfb111ff1111cb111cf111bd1111dc111bffb1ffb111bfb111fb111dfb111ffffffddddddddddddddddddddddddddddddddddddddddfffffffffffffffffffffffffffffff
    fdddddddddddddffffd1cb1c1bc1df11fbf11cbcd1fb1d1dd1bdbdb1ffb1ffb1cb1f1bf1dfb1fff1bc1dfffffddddddddddddddddddddddddddddddddddddddddfffffffffffffffffffffffffffffff
    fdddddddfdddddffffd1ff1b1111bf1bfffcd11c1dfd1c1bd1bc1111cfb1ffb1fc1c1ffd1fb1ffc1111bfffffddddddddddddddddddddddddddddddddddddddddfffffffffffffffffffffffffffffff
    fdddddddfdddddffffd1cb1c1bfbcf1bfffdcf1dd1cb1c1bd1bd1db1cfb1ffb1fc1c1bc1dfb1cbf1bfbcfffffddddddddddddddddddddddddddddddddddddddddfffffffffffffffffffffffffffffff
    fdddddddfdddddffffd111dfb111bf1bfff1111cc111bd1cd1bb1111c1111bb1fc1fb111cfc111cb111bfffffddddddddddddddddddddddddddddddddddddddddfffffffffffffffffffffffffffffff
    fdddddddfdddddffffddccffffcccfffffffffffffcddddddddddcdfccffffffffffffcffffffffffcfcfffffddddddddddddddddddddddddddddddddddddddddfffffffffffffffffffffffffffffff
    fdddddddddddddffffbdfffffffffffffffffffffffddddddddddddffcfffffffffffffffffffffffffffffffddddddddddddddddddddddddddddddddddddddddfffffffffffffffffffffffffffffff
    fdddddddddddddfffffffffffffffffffffffffffffddddddddddddffffffffffffffffffffffffffffffffffddddddddddddddddddddddddddddddddddddddddfffffffffffffffffffffffffffffff
    fdddddddddddddffffffffffffffffffffffffffffffdddddddddddffffffffffffffffffffffffffffffffffddddddddddddddddddddddddddddddddddddddddfffffffffffffffffffffffffffffff
    fdddddddddddddffffffffffffffffffffffffffffffdddddddddddffffffffffffffffffffffffffffffffffddddddddddddddddddddddddddddddddddddddddfffffffffffffffffffffffffffffff
    fdddddddddddddffffffffffffffffffffffffffffffdddddddddddffffffffffffffffffffffffffffffffffddddddddddddddddddddddddddddddddddddddddfffffffffffffffffffffffffffffff
    fdddddddddddddffffffffffffffffffffffffffffffdddddddddddffffffffffffffffffffffffffffffffffddddddddddddddddddddddddddddddddddddddddfffffffffffffffffffffffffffffff
    fddddddddddddddfffffffffffffffffffffffffffffdddddddddddffffffffffffffffffffffffffffffffffdddddddddddddddddddffdddddddddddddddddddffdffffffffffffffffffffffffffff
    fddddddddddddddfffffffffffffffffffffffdfffffdddddddddddffffffffffffffffffffffffffffffffffddddddddddddddddddfffdddddddddddddddddddfffffffffffffffffffffffffffffff
    fddddddddddddddfffffffffffffffffffffffffffffdddddddddddffffffffffffffffffffffffffffffffffddddddddddddddddddfffdddddddddddddddddddffdffffffffffffffffffffffffffff
    fddddddddddddddfffffffffffffffffffffffffffffdddddddddddffffffffffffffffffffffffffffffffffdddddddddddddddddddffdddddddddddddddddddffdffffffffffffffffffffffffffff
    fddddddddddddddffffffffffffffffffffffffffffffddddddddddffffffffffffffffffffffffffffffffffddddddddddddddddddddddddddddddddddddddddffdffffffffffffffffffffffffffff
    fddddddddddddddffffffffffffffffffffffffffffffddddddddddffffffffffffffffffffffffffffffffffdddddddfddddddddddddddddddddddddddddddddfffffffffffffffffffffffffffffff
    fddddddddddddddffffffffffffffffffffffffffffffddddddddddffffffffffffffffffffffffffffffffffdddddddfddddddddddddddddddddddddddddddddfffffffffffffffffffffffffffffff
    fddddddddddddddfffffffffffffffffffffffffffffdddddddddddffffffffffffffffffffffffffffffffffdddddddfddddddddddddddddddddddddddddddddfffffffffffffffffffffffffffffff
    fddddddddddddddfffffffffffffffffffffffffffffdddddddddddffffffffffffffffffffffffffffffffffdddddddfddddddddddddddddddddddddddddddddfffffffffffffffffffffffffffffff
    fddddddddddddddfffffffffffffffffffffffffffffdddddddddddffffffffffffffffffffffffffffffffffdddddddfddddddddddddddddddddddddddddddddfffffffffffffffffffffffffffffff
    fddddddddddddddfffffffffffffffffffffffffffffdddddddddddffffffffffffffffffffffffffffffffffdddddddfddddddddddddddddddddddddddddddddfffffffffffffffffffffffffffffff
    fddddddddddddddfffffffffffffffffffffffffffffdddddddddddffffffffffffffffffffffffffffffffffddddddffddddddddddddddddddddddddddddddddfffffffffffffffffffffffffffffff
    fddddddddddddddfffffffffffffffffffffffffffffdddddddddddffffffffffffffffffffffffffffffffffddddddffddddddddddddddddddddddddddddddddfffffffffffffffffffffffffffffff
    fddddddddddddddfffffffffffffffffffffffffffffdddddddddddffffffffffffffffffffffffffffffffffddddddffddddddddddddddddddddddddddddddddfffffffffffffffffffffffffffffff
    fddddddddddddddfffffffffffffffffffffffffffffdddddddddddffffffffffffffffffffffffffffffffffddddddffddddddddddddddddddddddddddddddddfffffffffffffffffffffffffffffff
    fddddddddddddddffffffffffffffffffffffffffffffddddddddddffffffffffffffffffffffffffffffffffddddddffddddddddddddddddddddddddddddddddfffffffffffffffffffffffffffffff
    fddddddddddddddffffffffffffffffffffffffffffffddddddddddffffffffffffffffffffffffffffffffffddddddffdddddddddddddddddddddddddddddddffffffffffffffffffffffffffffffff
    fddddddddddddddffffffffffffffffffffffffffffffddddddddddffffffffffffffffffffffffffffffffffddddddffdddddddddddddddddddddddddddddddffffffffffffffffffffffffffffffff
    fddddddddddddddffffffffffffffffffffffffffffffdddddddddddfffffffffffffffffffffffffffffffffddddddffdddddddddddddddddddddddddddddddffffffffffffffffffffffffffffffff
    fdddddddddddddddfffffffffffffffffffffffffffffdddddddddddfffffffffffffffffffffffffffffffffddddddffdddddddddddddddddddddddddddddddffffffffffffffffffffffffffffffff
    fdddddddddddddddfffffffffffffffffffffffffffffdddddddddddfffffffffffffffffffffffffffffffffddddddffddddddddddddddddddddddddddddddddfffffffffffffffffffffffffffffff
    fdddddddddddddddfffffffffffffffffffffffffffffdddddddddddfffffffffffffffffffffffffffffffffddddddffddddddddddddddddddddddddddddddddfffffffffffffffffffffffffffffff
    fdddddddddddddddfffffffffffffffffffffffffffffdddddddddddfffffffffffffffffffffffffffffffffddddddffdddddddddddddddddddddffddddddddffffffffffffffffffffffffffffffff
    fdddddddddddddddfffffffffffffffffffffffffffffdddddddddddfffffffffffffffffffffffffffffffffddddddffdddddddddddddddddddddfffdddddddffffffffffffffffffffffffffffffff
    fddddddddfddddddfffffffffffffffffffffffffffffddddddddddffffffffffffffffffffffffffffffffffdddddddddddddddddfffddddddffffffffdddddffffffffffffffffffffffffffffffff
    fddddddddfddddddfffffffffffffffffffffffffffffdddddddddddfffffffffffffffffffffffffffffffffdddddddddddddddddfffddddddffffffffdddddffffffffffffffffffffffffffffffff
    fddddddddfddddddfffffffffffffffffffffffffffffddddfddddddfffffffffffffffffffffffffffffffffdddddddddddddddddfffddddddfffffffffffffffffffffffffffffffffffffffffffff
    fdddddddddddddddfffffffffffffffffffffffffffffddddfddddddfffffffffffffffffffffffffffffffffdddddddddddddddddfffddddddfffffffffffffffffffffffffffffffffffffffffffff
    fdddddddddddddddfffffffffffffffffffffffffffffdddddddddddfffffffffffffffffffffffffffffffffdddddddddddddddddfffddddddfffffffffffffffffffffffffffffffffffffffffffff
    fdddddddddddddddffffffffffffffffffffffffffffffddddddddddffffffffffffffffffffffffffffffffffddddddddddddffffffdfddddffffffffffffffffffffffffffffffffffffffffffffff
    fdddddddddddddddffffffffffffffffffffffffffffffdddddddddffffffffffffffffffffffffffffffffffffdddddffddfdffffffffddddffffffffffffffffffffffffffffffffffffffffffffff
    fdddddddddddddddffffffffffffffffffffffffffffffdddddddddfffffffffffffffffffffffffffffffffffffffffffddffffffffffddddffffffffffffffffffffffffffffffffffffffffffffff
    fdddddddddddddddffffffffffffffffffffffffffffffdddddddddfffffffffffffffffffffffffffffffffffffffffffddffffffffffdfddffffffffffffffffffffffffffffffffffffffffffffff
    fdddddddddddddddffffffffffffffffffffffffffffffddddddddfffffffffffffffffffffffffffffffffffffffffffffdffffffffffdfddffffffffffffffffffffffffffffffffffffffffffffff
    fdddddddddddddddffffffffffffffffffffffffffffffddddffffffffffffffffffffffffffffffffffffffffffffffffddffffffffffdddfffffffffffffffffffffffffffffffffffffffffffffff
    fddddddfddddddddffffffffffffffffffffffffffffffddddfffffffffffffffffffffffffffffffffffffffffffffffffdffffffffffdddfffffffffffffffffffffffffffffffffffffffffffffff
    fddddddfddffddddffffffffffffffffffffffffffffffddddffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffdddfffffffffffffffffffffffffffffffffffffffffffffff
    fddddddfddffddddffffffffffffffffffffffffffffffddddffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffdddfffffffffffffffffffffffffffffffffffffffffffffff
    fddddddfddffddddffffffffffffffffffffffffffffffddddffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffdddfffffffffffffffffffffffffffffffffffffffffffffff
    fddddddddddddddddfffffffffffffffffffffffffffffdddffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffddfffffffffffffffffffffffffffffffffffffffffffffff
    fddddddddddddddddfffffffffffffffffffffffffffffdddffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffddfffffffffffffffffffffffffffffffffffffffffffffff
    fddddddddddddddddfffffffffffffffffffffffffffffdddffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffddfffffffffffffffffffffffffffffffffffffffffffffff
    fddddddddddddddddfffffffffffffffffffffffffffffdddffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffddfffffffffffffffffffffffffffffffffffffffffffffff
    fddddddddddddddddfffffffffffffffffffffffffffffdddffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffddfffffffffffffffffffffffffffffffffffffffffffffff
    fddddddddddddddddffffffffffffffffffffffffffffffddffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffddfffffffffffffffffffffffffffffffffffffffffffffff
    `, SpriteKind.UI)
game.setDialogFrame(img`
    . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . 
    `)
game.setDialogCursor(img`
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    `)
game.showLongText("", DialogLayout.Bottom)
tiles.setCurrentTilemap(tilemap`level2`)
Render.changeBrightness(3, 1.4)
